#ARG base_image=crmdvrepo01.azurecr.io/wildfly:310122

ARG baseImageUri
ARG baseImageTag
FROM ${baseImageUri}:${baseImageTag}

ARG version
ARG mavenArtifactBaseUrl
ARG camunda_liquibase_version=17.21.1
ARG wildfly_home=/opt/jboss/wildfly
ARG wildfly_user=jboss
ARG context_group_name=boxworkmanagement
ARG context_name=boxworkmanagement
ARG framework_version=17.101.6
ARG eventstore_version=17.101.5

ADD ${mavenArtifactBaseUrl}/uk/gov/moj/cpp/${context_group_name}/${context_name}-service/${version}/${context_name}-service-${version}.war ${wildfly_home}/standalone/deployments/
USER root
RUN chown -R ${wildfly_user}:${wildfly_user} ${wildfly_home}/standalone/deployments/ && chmod -R 700 ${wildfly_home}/standalone/deployments/

# liquibase jars & config
RUN mkdir /tmp/liquibase
ADD ${mavenArtifactBaseUrl}/uk/gov/moj/cpp/camunda/camunda-liquibase/${camunda_liquibase_version}/camunda-liquibase-${camunda_liquibase_version}.jar /tmp/liquibase/camunda-liquibase.jar
RUN chmod -R 755 /tmp/liquibase
COPY scripts/liquibase.sh /tmp/liquibase/liquibase.sh
RUN chown ${wildfly_user}:${wildfly_user} /tmp/liquibase/liquibase.sh && chmod 755 /tmp/liquibase/liquibase.sh
RUN mkdir /opt/cpp-tools
ADD ${mavenArtifactBaseUrl}/uk/gov/justice/services/framework-jmx-command-client/${framework_version}/framework-jmx-command-client-${framework_version}.jar /opt/cpp-tools/framework-jmx-command-client.jar
RUN chown ${wildfly_user}:${wildfly_user} /opt/cpp-tools/framework-jmx-command-client.jar && chmod 755 /opt/cpp-tools/framework-jmx-command-client.jar
USER ${wildfly_user}
LABEL base_image ${baseImageTag}